version: "3.5"

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: exemple
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  db-data:
    driver: local

networks:
  backend:
    name: kitchen_backend
    driver: bridge
