version: "3.8"
services:
  api:
    container_name: backend
    build:
      context: ../../api
      dockerfile: ../docker/homol/Dockerfile
#   restart: always
    ports:
      - "8081:8080"

#volumes:
#  db-data:
#    driver: local
