version: "3.5"
services:
  api:
    container_name: backend
    build:
      context: ../../api
      dockerfile: ../docker/homol/Dockerfile
#   restart: always
    ports:
      - "8081:8080"
    networks:
      - backend

networks:
  backend:
    name: kitchen_backend
    driver: bridge
